"""
Integration tests against real data fixtures from hawkins2020_characterizing_cued.

Fixtures are generated by running:
    .venv/bin/python script/run_pipeline.py

Tests are skipped if fixtures don't exist so CI without Redivis access still passes.
"""
import io
import os

import numpy as np
import pytest

FIXTURES = os.path.join(os.path.dirname(__file__), "..", "fixtures")


def _fixture(*parts) -> str:
    return os.path.join(FIXTURES, *parts)


def _fixtures_present() -> bool:
    return all(
        os.path.exists(_fixture(f))
        for f in ("hawkins2020_5games.parquet", "hawkins2020_images.npz", "hawkins2020_texts.npz")
    )


needs_fixtures = pytest.mark.skipif(
    not _fixtures_present(),
    reason="Real-data fixtures missing — run script/run_pipeline.py first",
)


# ---------------------------------------------------------------------------
# Fixture loading helpers (shared across tests)
# ---------------------------------------------------------------------------

def _load_batch():
    import pandas as pd
    from code.prep_data.pipeline import build_trial_batch_from_df

    df = pd.read_parquet(_fixture("hawkins2020_5games.parquet"))
    img_npz = np.load(_fixture("hawkins2020_images.npz"))
    txt_npz = np.load(_fixture("hawkins2020_texts.npz"))
    image_embs = {k: img_npz[k] for k in img_npz.files}
    text_embs  = {k: txt_npz[k] for k in txt_npz.files}
    return build_trial_batch_from_df(df, image_embs, text_embs)


# ---------------------------------------------------------------------------
# SVG encoding — regression for PIL.UnidentifiedImageError on SVG stimuli
# ---------------------------------------------------------------------------

@pytest.mark.slow
def test_clip_encoder_handles_svg(tmp_path):
    """CLIPEncoder must rasterize SVG files rather than crashing with PIL."""
    from code.embeddings.clip_encoder import CLIPEncoder

    svg_content = (
        '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100">'
        '<rect width="100" height="100" fill="steelblue"/>'
        "</svg>"
    )
    svg_path = str(tmp_path / "test.svg")
    with open(svg_path, "w") as f:
        f.write(svg_content)

    encoder = CLIPEncoder()
    embs = encoder.encode_images([svg_path])

    assert embs.shape == (1, 512), f"Expected (1, 512), got {embs.shape}"
    assert abs(np.linalg.norm(embs[0]) - 1.0) < 1e-4, "Embedding should be L2-normalized"


# ---------------------------------------------------------------------------
# Literal listener on real data
# ---------------------------------------------------------------------------

@pytest.mark.slow
@needs_fixtures
def test_listener_fit_on_real_data():
    """Literal listener SVI completes without NaN on the 5-game fixture."""
    from code.models.literal_listener import fit_listener

    batch = _load_batch()
    fit = fit_listener(batch, n_steps=200, seed=0)

    assert fit.beta_loc.shape == (batch.n_listeners,)
    assert not np.any(np.isnan(fit.beta_loc)), "NaN in posterior beta means"
    assert not np.any(np.isnan(fit.beta_scale)), "NaN in posterior beta scales"


# ---------------------------------------------------------------------------
# Convention model on real data — regression for NaN with binary s_t
# ---------------------------------------------------------------------------

@pytest.mark.slow
@needs_fixtures
def test_convention_fit_stable_on_real_data():
    """
    Convention model SVI (both speaker and listener) must complete without NaN
    on the 5-game fixture.

    This is a regression test for the numerical instability that occurred when
    binary listener s_t values (0/1) produced extreme emission variances at
    D=512 without gradient clipping.
    """
    from code.models.literal_listener import fit_listener
    from code.models.conventional_speaker import compute_r1_average, fit_convention

    batch = _load_batch()
    listener_fit = fit_listener(batch, n_steps=200, seed=0)
    mu_i_init = compute_r1_average(batch)
    fit = fit_convention(batch, listener_fit, mu_i_init, n_steps=200, seed=0)

    assert fit.speaker_m_loc.shape == (batch.n_games, batch.n_images, 512)
    assert fit.listener_m_loc.shape == (batch.n_games, batch.n_images, 512)
    assert not np.any(np.isnan(fit.speaker_m_loc)), "NaN in speaker convention means"
    assert not np.any(np.isnan(fit.listener_m_loc)), "NaN in listener convention means"
    assert fit.sigma_game > 0
    assert fit.sigma_min > 0
    assert fit.sigma_max > 0


# ---------------------------------------------------------------------------
# Analysis on real data
# ---------------------------------------------------------------------------

@pytest.mark.slow
@needs_fixtures
def test_step_sizes_return_dataframe_on_real_data():
    """step_sizes_over_reps runs without error on real data and has expected columns."""
    from code.models.literal_listener import fit_listener
    from code.models.conventional_speaker import compute_r1_average, fit_convention
    from code.analysis.predictions import step_sizes_over_reps

    batch = _load_batch()
    listener_fit = fit_listener(batch, n_steps=200, seed=0)
    mu_i_init = compute_r1_average(batch)
    fit = fit_convention(batch, listener_fit, mu_i_init, n_steps=200, seed=0)

    df = step_sizes_over_reps(fit, batch, role="speaker")
    assert set(df.columns) == {"game_id", "image_id", "rep_num", "step_size"}
    assert len(df) > 0
    assert not df["step_size"].isna().any()
